title: Nobody's personal site
email: az8321550@gmail.com
description: >
  Hey guys. My name is Body No. This is my blog. Build by jekyll.
  Since I was young. I liked play computer game.
  And wondering how the game created.
  I had mass interested at it.
  Then when I was 18 years old.
  I began coding.
  A computer engineer.
  Because I like it. Just do it. No regret.

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page/:num"
url: "https://nobody.kdk.fun"
enforce_ssl: nobody.kdk.fun
future: true
twitter_username: az8321550
github_username:  bodyno
markdown: kramdown
