# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nobody's personal site
email: az8321550@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey guys. My name is Body No. This is my blog. Build by jekyll.
  Since I was young. I liked play computer game.
  And wondering how the game created.
  I had mass interested at it.
  Then when I was 18 years old.
  I began coding.
  A computer engineer.
  Because I like it. Just do it. No regret.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: az8321550
github_username:  az8321550

# Build settings
markdown: kramdown
